services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: bun run dev

volumes:
  node_modules:
