import React from 'react'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { Header } from "./_components/header"
import { Sidebar } from "./_components/sidebar"

import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                {/* {children} */}
                <div className="min-h-screen bg-background">
                    {/* Desktop sidebar */}
                    <div className="hidden lg:block">
                        <Sidebar />
                    </div>

                    {/* Main content */}
                    <div className="lg:pl-64">
                        <Header />
                        <main className="p-4 lg:p-6">{children}</main>
                    </div>
                </div>
            </body>
        </html>
    )
}

export default RootLayout